var today = new Date();
var y = today.getFullYear();
var m = today.getMonth();
var d = today.getDate();

const events = [
  {
    id: 1,
    title: "Call with Dave",
    start: new Date(y, m, 1),
    allDay: true,
    classusername: "bg-red",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 2,
    title: "Lunch meeting",
    start: new Date(y, m, d - 1, 10, 30),
    allDay: true,
    classusername: "bg-orange",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 3,
    title: "All day conference",
    start: new Date(y, m, d + 7, 12, 0),
    allDay: true,
    classusername: "bg-green",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 4,
    title: "Meeting with Mary",
    start: new Date(y, m, d - 2),
    allDay: true,
    classusername: "bg-blue",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 5,
    title: "Winter Hackaton",
    start: new Date(y, m, d + 1, 19, 0),
    allDay: true,
    classusername: "bg-red",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 6,
    title: "Digital event",
    start: new Date(y, m, 21),
    allDay: true,
    classusername: "bg-warning",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 7,
    title: "Marketing event",
    start: new Date(y, m, 21),
    allDay: true,
    classusername: "bg-purple",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 8,
    title: "Dinner with Family",
    start: new Date(y, m, 19),
    allDay: true,
    classusername: "bg-red",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 9,
    title: "Black Friday",
    start: new Date(y, m, 23),
    allDay: true,
    classusername: "bg-blue",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },

  {
    id: 10,
    title: "Cyber Week",
    start: new Date(y, m, 2),
    allDay: true,
    classusername: "bg-yellow",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
];

// ##############################
// // // data for populating the calendar in Widgest view
// #############################

const widgetEvents = [
  {
    title: "Lunch meeting",
    start: new Date().getFullYear() + "-11-21",
    end: new Date().getFullYear() + "-11-22",
    classusername: "bg-orange",
  },
  {
    title: "All day conference",
    start: new Date(y, m - 1, 28),
    allDay: true,
    classusername: "bg-green",
  },
  {
    title: "Meeting with Mary",
    start: new Date(y, m, 2),
    allDay: true,
    classusername: "bg-blue",
  },
  {
    title: "Winter Hackaton",
    start: new Date(y, m, 4),
    allDay: true,
    classusername: "bg-red",
  },
  {
    title: "Digital event",
    start: new Date(y, m, 8),
    end: new Date(y, m, 10),
    allDay: true,
    classusername: "bg-warning",
  },
  {
    title: "Marketing event",
    start: new Date(y, m, 11),
    allDay: true,
    classusername: "bg-purple",
  },
  {
    title: "Dinner with Family",
    start: new Date(y, m, 20),
    allDay: true,
    classusername: "bg-red",
  },
  {
    title: "Black Friday",
    start: new Date(y, m, 24),
    allDay: true,
    classusername: "bg-blue",
  },
  {
    title: "Cyber Week",
    start: new Date(y, m, 3),
    allDay: true,
    classusername: "bg-yellow",
  },
];

// ##############################
// // // data for populating the table in ReactTables view
// #############################

const dataTable = [
  {
    id: "#1",
    username: "Tiger Nixon",
    email: "System Architect",
    address: "Edinburgh",
    status: "61",
    start_date: "2011/04/25",
    salary: "$320,800",
  },
  {
    id: "#2",
    username: "Garrett Winters",
    email: "Accountant",
    address: "Tokyo",
    status: "63",
    start_date: "2011/07/25",
    salary: "$170,750",
  },
  {
    username: "Ashton Cox",
    email: "Junior Technical Author",
    address: "San Francisco",
    status: "66",
    start_date: "2009/01/12",
    salary: "$86,000",
  },
  {
    username: "Cedric Kelly",
    email: "Senior Javascript Developer",
    address: "Edinburgh",
    status: "22",
    start_date: "2012/03/29",
    salary: "$433,060",
  },
  {
    username: "Airi Satou",
    email: "Accountant",
    address: "Tokyo",
    status: "33",
    start_date: "2008/11/28",
    salary: "$162,700",
  },
  {
    username: "Brielle Williamson",
    email: "Integration Specialist",
    address: "New York",
    status: "61",
    start_date: "2012/12/02",
    salary: "$372,000",
  },
  {
    username: "Herrod Chandler",
    email: "Sales Assistant",
    address: "San Francisco",
    status: "59",
    start_date: "2012/08/06",
    salary: "$137,500",
  },
  {
    username: "Rhona Davidson",
    email: "Integration Specialist",
    address: "Tokyo",
    status: "55",
    start_date: "2010/10/14",
    salary: "$327,900",
  },
  {
    username: "Colleen Hurst",
    email: "Javascript Developer",
    address: "San Francisco",
    status: "39",
    start_date: "2009/09/15",
    salary: "$205,500",
  },
  {
    username: "Sonya Frost",
    email: "Software Engineer",
    address: "Edinburgh",
    status: "23",
    start_date: "2008/12/13",
    salary: "$103,600",
  },
  {
    username: "Jena Gaines",
    email: "address Manstatusr",
    address: "London",
    status: "30",
    start_date: "2008/12/19",
    salary: "$90,560",
  },
  {
    username: "Quinn Flynn",
    email: "Support Lead",
    address: "Edinburgh",
    status: "22",
    start_date: "2013/03/03",
    salary: "$342,000",
  },
  {
    username: "Charde Marshall",
    email: "Regional Director",
    address: "San Francisco",
    status: "36",
    start_date: "2008/10/16",
    salary: "$470,600",
  },
  {
    username: "Haley Kennedy",
    email: "Senior Marketing Designer",
    address: "London",
    status: "43",
    start_date: "2012/12/18",
    salary: "$313,500",
  },
  {
    username: "Tatyana Fitzpatrick",
    email: "Regional Director",
    address: "London",
    status: "19",
    start_date: "2010/03/17",
    salary: "$385,750",
  },
  {
    username: "Michael Silva",
    email: "Marketing Designer",
    address: "London",
    status: "66",
    start_date: "2012/11/27",
    salary: "$198,500",
  },
  {
    username: "Paul Byrd",
    email: "Chief Financial addressr (CFO)",
    address: "New York",
    status: "64",
    start_date: "2010/06/09",
    salary: "$725,000",
  },
  {
    username: "Gloria Little",
    email: "Systems Administrator",
    address: "New York",
    status: "59",
    start_date: "2009/04/10",
    salary: "$237,500",
  },
  {
    username: "Bradley Greer",
    email: "Software Engineer",
    address: "London",
    status: "41",
    start_date: "2012/10/13",
    salary: "$132,000",
  },
  {
    username: "Dai Rios",
    email: "Personnel Lead",
    address: "Edinburgh",
    status: "35",
    start_date: "2012/09/26",
    salary: "$217,500",
  },
  {
    username: "Jenette Caldwell",
    email: "Development Lead",
    address: "New York",
    status: "30",
    start_date: "2011/09/03",
    salary: "$345,000",
  },
  {
    username: "Yuri Berry",
    email: "Chief Marketing addressr (CMO)",
    address: "New York",
    status: "40",
    start_date: "2009/06/25",
    salary: "$675,000",
  },
  {
    username: "Caesar Vance",
    email: "Pre-Sales Support",
    address: "New York",
    status: "21",
    start_date: "2011/12/12",
    salary: "$106,450",
  },
  {
    username: "Doris Wilder",
    email: "Sales Assistant",
    address: "Sidney",
    status: "23",
    start_date: "2010/09/20",
    salary: "$85,600",
  },
  {
    username: "Angelica Ramos",
    email: "Chief Executive addressr (CEO)",
    address: "London",
    status: "47",
    start_date: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    username: "Gavin Joyce",
    email: "Developer",
    address: "Edinburgh",
    status: "42",
    start_date: "2010/12/22",
    salary: "$92,575",
  },
  {
    username: "Jennifer Chang",
    email: "Regional Director",
    address: "Singapore",
    status: "28",
    start_date: "2010/11/14",
    salary: "$357,650",
  },
  {
    username: "Brenden Wagner",
    email: "Software Engineer",
    address: "San Francisco",
    status: "28",
    start_date: "2011/06/07",
    salary: "$206,850",
  },
  {
    username: "Fiona Green",
    email: "Chief Operating addressr (COO)",
    address: "San Francisco",
    status: "48",
    start_date: "2010/03/11",
    salary: "$850,000",
  },
  {
    username: "Shou Itou",
    email: "Regional Marketing",
    address: "Tokyo",
    status: "20",
    start_date: "2011/08/14",
    salary: "$163,000",
  },
  {
    username: "Michelle House",
    email: "Integration Specialist",
    address: "Sidney",
    status: "37",
    start_date: "2011/06/02",
    salary: "$95,400",
  },
  {
    username: "Suki Burks",
    email: "Developer",
    address: "London",
    status: "53",
    start_date: "2009/10/22",
    salary: "$114,500",
  },
  {
    username: "Prescott Bartlett",
    email: "Technical Author",
    address: "London",
    status: "27",
    start_date: "2011/05/07",
    salary: "$145,000",
  },
  {
    username: "Gavin Cortez",
    email: "Team Leader",
    address: "San Francisco",
    status: "22",
    start_date: "2008/10/26",
    salary: "$235,500",
  },
  {
    username: "Martena Mccray",
    email: "Post-Sales support",
    address: "Edinburgh",
    status: "46",
    start_date: "2011/03/09",
    salary: "$324,050",
  },
  {
    username: "Unity Butler",
    email: "Marketing Designer",
    address: "San Francisco",
    status: "47",
    start_date: "2009/12/09",
    salary: "$85,675",
  },
  {
    username: "Howard Hatfield",
    email: "address Manstatusr",
    address: "San Francisco",
    status: "51",
    start_date: "2008/12/16",
    salary: "$164,500",
  },
  {
    username: "Hope Fuentes",
    email: "Secretary",
    address: "San Francisco",
    status: "41",
    start_date: "2010/02/12",
    salary: "$109,850",
  },
  {
    username: "Vivian Harrell",
    email: "Financial Controller",
    address: "San Francisco",
    status: "62",
    start_date: "2009/02/14",
    salary: "$452,500",
  },
  {
    username: "Timothy Mooney",
    email: "address Manstatusr",
    address: "London",
    status: "37",
    start_date: "2008/12/11",
    salary: "$136,200",
  },
  {
    username: "Jackson Bradshaw",
    email: "Director",
    address: "New York",
    status: "65",
    start_date: "2008/09/26",
    salary: "$645,750",
  },
  {
    username: "Olivia Liang",
    email: "Support Engineer",
    address: "Singapore",
    status: "64",
    start_date: "2011/02/03",
    salary: "$234,500",
  },
  {
    username: "Bruno Nash",
    email: "Software Engineer",
    address: "London",
    status: "38",
    start_date: "2011/05/03",
    salary: "$163,500",
  },
  {
    username: "Sakura Yamamoto",
    email: "Support Engineer",
    address: "Tokyo",
    status: "37",
    start_date: "2009/08/19",
    salary: "$139,575",
  },
  {
    username: "Thor Walton",
    email: "Developer",
    address: "New York",
    status: "61",
    start_date: "2013/08/11",
    salary: "$98,540",
  },
  {
    username: "Finn Camacho",
    email: "Support Engineer",
    address: "San Francisco",
    status: "47",
    start_date: "2009/07/07",
    salary: "$87,500",
  },
  {
    username: "Serge Baldwin",
    email: "Data Coordinator",
    address: "Singapore",
    age: "64",
    start_date: "2012/04/09",
    salary: "$138,575",
  },
];

export { events, widgetEvents, dataTable };
